apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../config/default

images:
- name: ghcr.io/danieljcheung/previewapp-controller
  newName: ghcr.io/danieljcheung/previewapp-controller
  newTag: ae8a97a73d36826382986c56b395a5cc3b0aa5c0
