apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../config/default

images:
- name: ghcr.io/danieljcheung/previewapp-controller
  newName: ghcr.io/danieljcheung/previewapp-controller
  newTag: fe873285833a6b5285033d1073799ea039750541
