# This rule is not used by the project previewapp itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the previewapp.danieljcheung.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: previewapp
    app.kubernetes.io/managed-by: kustomize
  name: previewapp-editor-role
rules:
- apiGroups:
  - previewapp.danieljcheung.com
  resources:
  - previewapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - previewapp.danieljcheung.com
  resources:
  - previewapps/status
  verbs:
  - get
