# This rule is not used by the project previewapp itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to previewapp.danieljcheung.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: previewapp
    app.kubernetes.io/managed-by: kustomize
  name: previewapp-viewer-role
rules:
- apiGroups:
  - previewapp.danieljcheung.com
  resources:
  - previewapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - previewapp.danieljcheung.com
  resources:
  - previewapps/status
  verbs:
  - get
