apiVersion: previewapp.danieljcheung.com/v1alpha1
kind: PreviewApp
metadata:
  name: hello
  namespace: previews
  labels:
    app.kubernetes.io/name: popinvites-hello
    app.kubernetes.io/part-of: popinvites
spec:
  image: ghcr.io/danieljcheung/popinvites-hello@sha256:1172dad6fb1310fa02bbda7eccff0730dcc364c822bb9caf8c3386ddfb62b0a2
  appPort: 8080
  ttlSeconds: 2592000
  route:
    host: hello
